"""
Prometheus Metrics Instrumentation for CloudServe Support System.

Build ID: B-12-PROM
Requirement: Real-time observability, telemetry, and runtime monitoring.

Exposes comprehensive Prometheus metrics for:
- Ticket throughput and in-flight tracking
- Pipeline stage latencies (classify, retrieve, route, generate, validate)
- Classification intent & confidence distributions
- Retrieval chunk counts and similarity scores
- Routing decisions & policy compliance (must-not-auto-respond)
- Response generation & citation metrics
- Guardrail evaluations and failed safety checks
- System error categories and rate limit wait times
"""

import logging
import time
from contextlib import contextmanager
from typing import Optional

from prometheus_client import (
    CollectorRegistry,
    Counter,
    Gauge,
    Histogram,
    REGISTRY,
    generate_latest,
    start_http_server,
)

logger = logging.getLogger(__name__)

# Use default registry or custom registry
registry: CollectorRegistry = REGISTRY

# ---------------------------------------------------------------------------
# Metric Definitions
# ---------------------------------------------------------------------------

# 1. Ticket Processing & Throughput
TICKETS_TOTAL = Counter(
    "cloudserve_tickets_total",
    "Total number of tickets processed by the pipeline",
    ["channel", "tier", "status", "final_action"],
    registry=registry,
)

TICKETS_IN_FLIGHT = Gauge(
    "cloudserve_tickets_in_flight",
    "Number of tickets currently being processed in the pipeline",
    ["channel"],
    registry=registry,
)

TICKET_PROCESSING_SECONDS = Histogram(
    "cloudserve_ticket_processing_seconds",
    "Total processing time per ticket through the pipeline",
    buckets=[0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 30.0, 60.0, 120.0],
    registry=registry,
)

# 2. Stage Latencies
STAGE_DURATION_SECONDS = Histogram(
    "cloudserve_stage_duration_seconds",
    "Execution time for each pipeline stage node",
    ["stage"],
    buckets=[0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 30.0],
    registry=registry,
)

# 3. Classification Metrics
CLASSIFICATION_INTENT_TOTAL = Counter(
    "cloudserve_classification_intent_total",
    "Intent classifications by predicted intent, urgency, and answerability",
    ["intent", "urgency", "answerable"],
    registry=registry,
)

CLASSIFICATION_CONFIDENCE = Histogram(
    "cloudserve_classification_confidence",
    "Confidence score distribution from LLM classification",
    ["dimension"],  # "intent", "urgency", "answerable"
    buckets=[0.0, 0.3, 0.5, 0.6, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0],
    registry=registry,
)

# 4. Retrieval Metrics
RETRIEVAL_CHUNKS_COUNT = Histogram(
    "cloudserve_retrieval_chunks_count",
    "Number of documentation chunks retrieved from vector store",
    buckets=[0, 1, 2, 3, 4, 5, 8, 10],
    registry=registry,
)

RETRIEVAL_RELEVANCE_SCORE = Histogram(
    "cloudserve_retrieval_relevance_score",
    "Relevance score of retrieved documentation chunks",
    buckets=[0.0, 0.2, 0.4, 0.5, 0.6, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0],
    registry=registry,
)

# 5. Routing & Policy Compliance
ROUTING_DECISIONS_TOTAL = Counter(
    "cloudserve_routing_decisions_total",
    "Routing decisions made by the deterministic router",
    ["action", "rule_triggered", "escalation_target"],
    registry=registry,
)

POLICY_COMPLIANCE_TOTAL = Counter(
    "cloudserve_policy_compliance_total",
    "Compliance with critical safety routing policies",
    ["policy", "compliant"],  # policy="must_not_auto_respond", compliant="true"/"false"
    registry=registry,
)

# 6. Response Generation
GENERATION_TOTAL = Counter(
    "cloudserve_generation_total",
    "Number of responses generated by LLM",
    ["could_answer", "model"],
    registry=registry,
)

GENERATION_CITATIONS_COUNT = Histogram(
    "cloudserve_generation_citations_count",
    "Number of document citations in generated response",
    buckets=[0, 1, 2, 3, 4, 5, 8],
    registry=registry,
)

# 7. Guardrails & Safety Checks
GUARDRAILS_EVALUATIONS_TOTAL = Counter(
    "cloudserve_guardrails_evaluations_total",
    "Guardrail validation outcomes",
    ["passed", "action"],  # passed="true"/"false", action="sent"/"blocked_by_guardrails"
    registry=registry,
)

GUARDRAILS_CHECKS_TOTAL = Counter(
    "cloudserve_guardrails_checks_total",
    "Individual guardrail check evaluations",
    ["check_name", "passed", "severity"],
    registry=registry,
)

# 8. Errors & Rate Limits
ERRORS_TOTAL = Counter(
    "cloudserve_errors_total",
    "Pipeline and stage error occurrences",
    ["error_type", "stage"],
    registry=registry,
)

RATE_LIMIT_EVENTS_TOTAL = Counter(
    "cloudserve_rate_limit_events_total",
    "Number of rate limit backoff events encountered",
    ["provider"],
    registry=registry,
)

RATE_LIMIT_WAIT_SECONDS_TOTAL = Counter(
    "cloudserve_rate_limit_wait_seconds_total",
    "Total seconds spent sleeping in rate limit exponential backoff",
    registry=registry,
)

# ---------------------------------------------------------------------------
# Timing & Helper Utilities
# ---------------------------------------------------------------------------

@contextmanager
def track_in_flight(channel: str = "unknown"):
    """Context manager to track active tickets in flight."""
    TICKETS_IN_FLIGHT.labels(channel=channel).inc()
    try:
        yield
    finally:
        TICKETS_IN_FLIGHT.labels(channel=channel).dec()


@contextmanager
def track_stage_duration(stage: str):
    """Context manager to measure and observe duration of a pipeline stage."""
    start_time = time.time()
    try:
        yield
    finally:
        duration = time.time() - start_time
        STAGE_DURATION_SECONDS.labels(stage=stage).observe(duration)


def record_classification_metrics(classification):
    """Record metrics from a ClassificationResult object."""
    if not classification:
        return

    CLASSIFICATION_INTENT_TOTAL.labels(
        intent=classification.intent or "unknown",
        urgency=classification.urgency or "unknown",
        answerable=str(bool(classification.answerable_from_docs)).lower(),
    ).inc()

    if classification.intent_confidence is not None:
        CLASSIFICATION_CONFIDENCE.labels(dimension="intent").observe(
            float(classification.intent_confidence)
        )
    if classification.urgency_confidence is not None:
        CLASSIFICATION_CONFIDENCE.labels(dimension="urgency").observe(
            float(classification.urgency_confidence)
        )
    if classification.answerable_confidence is not None:
        CLASSIFICATION_CONFIDENCE.labels(dimension="answerable").observe(
            float(classification.answerable_confidence)
        )


def record_retrieval_metrics(retrieval):
    """Record metrics from a RetrievalResult object."""
    if not retrieval:
        return

    RETRIEVAL_CHUNKS_COUNT.observe(retrieval.num_results)
    for chunk in retrieval.chunks:
        RETRIEVAL_RELEVANCE_SCORE.observe(float(chunk.relevance_score))


def record_routing_metrics(route_decision, ground_truth=None):
    """Record metrics from a RouteDecision object and policy compliance."""
    if not route_decision:
        return

    action_val = getattr(route_decision.action, "value", str(route_decision.action))
    rule_val = route_decision.rule_triggered or "none"
    target_val = route_decision.escalation_target or "none"

    ROUTING_DECISIONS_TOTAL.labels(
        action=action_val,
        rule_triggered=rule_val,
        escalation_target=target_val,
    ).inc()

    # Track policy compliance if ground truth is known
    if ground_truth:
        must_not_auto = ground_truth.get("must_not_auto_respond", False)
        if must_not_auto:
            is_compliant = action_val == "escalate"
            POLICY_COMPLIANCE_TOTAL.labels(
                policy="must_not_auto_respond",
                compliant=str(is_compliant).lower(),
            ).inc()


def record_generation_metrics(generation):
    """Record metrics from a GeneratedResponse object."""
    if not generation:
        return

    GENERATION_TOTAL.labels(
        could_answer=str(bool(generation.could_answer)).lower(),
        model=generation.model_used or "unknown",
    ).inc()

    num_citations = len(generation.cited_doc_ids) if generation.cited_doc_ids else 0
    GENERATION_CITATIONS_COUNT.observe(num_citations)


def record_guardrail_metrics(guardrail_result):
    """Record metrics from a GuardrailResult object."""
    if not guardrail_result:
        return

    is_passed = bool(guardrail_result.passed)
    final_action = "sent" if is_passed else "blocked_by_guardrails"

    GUARDRAILS_EVALUATIONS_TOTAL.labels(
        passed=str(is_passed).lower(),
        action=final_action,
    ).inc()

    for check in guardrail_result.checks:
        GUARDRAILS_CHECKS_TOTAL.labels(
            check_name=check.name or "unknown",
            passed=str(bool(check.passed)).lower(),
            severity=check.severity or "block",
        ).inc()


def record_ticket_completion(
    channel: str,
    tier: str,
    status: str,
    final_action: str,
    duration: float,
):
    """Record completion counters and latency for a ticket."""
    TICKETS_TOTAL.labels(
        channel=channel or "unknown",
        tier=tier or "unknown",
        status=status or "success",
        final_action=final_action or "unknown",
    ).inc()

    TICKET_PROCESSING_SECONDS.observe(duration)


def record_error(error_type: str, stage: str):
    """Record an error event."""
    ERRORS_TOTAL.labels(error_type=error_type, stage=stage).inc()


def record_rate_limit(provider: str, delay_seconds: float):
    """Record a rate-limit backoff event."""
    RATE_LIMIT_EVENTS_TOTAL.labels(provider=provider).inc()
    RATE_LIMIT_WAIT_SECONDS_TOTAL.inc(delay_seconds)


# ---------------------------------------------------------------------------
# Metrics Server / Exporter
# ---------------------------------------------------------------------------

_server_started = False


def start_metrics_server(port: int = 8000) -> bool:
    """
    Start a background HTTP server exposing Prometheus metrics at /metrics.

    Args:
        port: HTTP port to listen on (default: 8000)

    Returns:
        True if server started, False if already running.
    """
    global _server_started
    if _server_started:
        logger.debug("Prometheus metrics server is already running on port %d", port)
        return False

    try:
        start_http_server(port, registry=registry)
        _server_started = True
        logger.info("Prometheus metrics server running at http://0.0.0.0:%d/metrics", port)
        return True
    except Exception as e:
        logger.warning("Could not start Prometheus HTTP server on port %d: %s", port, e)
        return False


def get_latest_metrics() -> bytes:
    """Return latest prometheus metrics as bytes."""
    return generate_latest(registry)
